#! /bin/bash

export PANEL_HEIGHT=24
export PANEL_WM_NAME="bspwm_panel"
export PANEL_FONT="Iosevka"

# Utility functions
_check() {
    command -v "$1" > /dev/null
}

_bc() {
    bspc config "$@"
}

_br() {
    bspc rule "$@"
}

# BSPWM Desktop configurations
external_monitor=$(xrandr --query | grep 'HDMI-2' | cut -d' ' -f2)
if [[ $external_monitor == "disconnected" ]]; then
    bspc monitor eDP-1 --reset-desktops 1 2 3 4 5 6 7 8 9 0
else
    bspc monitor eDP-1 --reset-desktops 1 2 3 4 5
    bspc monitor HDMI-2 --reset-desktops 6 7 8 9 0
fi

# BSPWM Configurations and rules
_bc border_width            1
_bc window_gap              0
_bc focused_border_color    '#c74072'

_bc split_ratio          0.5
_bc borderless_monocle   false
_bc gapless_monocle      true

_br --add TelegramDesktop desktop=^8 state=floating rectangle=200x100+490-75
_br --add Matplotlib state=floating
_br --add matplotlib state=floating
_br --add Polybar layer=lower
_br --add Surf state=tiled
_br --add Emacs --one-shot desktop=^7 follow=on state=fullscreen
_br --add Slack desktop=^8 state=floating rectangle=800x600+100+30 follow=off

## Autostart applications and configs

# Parse my custom key mappings.  These enable Mod3 ("Hyper") and make
# some necessary adjustments to that end.  We need to evaluate this
# first otherwise it might mess up with SXHKD.
[ -f "$HOME"/.Xmodmap ] && xmodmap "$HOME"/.Xmodmap

if _check sxhkd; then
    pgrep -x sxhkd > /dev/null || sxhkd &
fi

if _check emacs; then
    ps -ef | grep "[e]macs --daemon" || emacs --daemon
fi

if _check dunst; then
    pgrep -x dunst > /dev/null || dunst &
fi

if _check picom; then
    pgrep picom > /dev/null || picom --experimental-backends &
fi

if _check feh; then
    if [ -e $HOME/.config/bin/theme ]; then
	$HOME/.config/bin/theme reset
    fi
fi

if _check panel; then
    pgrep lemonbar && pkill lemonbar
    $HOME/.config/bin/panel
fi
