#!/usr/bin/env bash

# Utility functions
_check() {
    command -v "$1" > /dev/null
}

_bc() {
    bspc config "$@"
}

_br() {
    bspc rule "$@"
}

# BSPWM Desktop configurations
external_monitor=$(xrandr --query | grep 'HDMI-2' | cut -d' ' -f2)
if [[ $external_monitor == "disconnected" ]]; then
    bspc monitor eDP-1 --reset-desktops I II III IV V VI VII VIII IX X
else
    bspc monitor eDP-1 --reset-desktops I II III IV V
    bspc monitor HDMI-2 --reset-desktops IV V VI VII VIII IX X
fi

# BSPWM Configurations and rules
_bc border_width            2
_bc window_gap              10
_bc focused_border_color    '#c74072'

_bc split_ratio          0.5
_bc borderless_monocle   false
_bc gapless_monocle      true

_br --add TelegramDesktop desktop=^8 state=floating centered=true rectangle=200x100
_br --add Emacs desktop=^7 state=fullscreen follow=on
_br --add Matplotlib state=floating
_br --add matplotlib state=floating
_br --add Polybar layer=lower

## Autostart applications and configs
if _check setxkbmap;then
    setxkbmap -option caps:ctrl_modifier
fi

if _check sxhkd; then
    pgrep -x sxhkd > /dev/null || sxhkd &
fi

if [[ $(ps -ef | grep "[e]macs --daemon") ]]; then
    emacs --daemon
fi

if _check feh; then
    if [ -n $HOME/.config/bin/theme ]; then
	$HOME/.config/bin/theme reset
    fi
fi

if _check picom;then
    picom --experimental-backends &
fi

if _check polybar;then
    bash $HOME/.config/polybar/launch.sh
fi

if _check dunst; then
    pgrep -x dunst > /dev/null || dunst &
fi
